// Shared glossary for ALL French lectures — function words every lesson reuses.
// Each lecture's own glossary spreads this and adds its specific words, so the
// tap-to-translate toolkit covers common words without duplicating entries.

export const BASE_GLOSSARY: Record<string, import('./frenchLessons').GlossaryEntry> = {
    // pronouns
    'je': { en: 'I', pron: 'zhuh', type: 'pronoun', register: 'neutral', note: 'becomes j\u2019 before a vowel: j\u2019ai, j\u2019habite' },
    'tu': { en: 'you', pron: 'tuu', type: 'pronoun', register: 'informal', note: 'friends, family, children — never strangers/elders' },
    'il': { en: 'he / it', pron: 'eel', type: 'pronoun', register: 'neutral' },
    'elle': { en: 'she / it', pron: 'ell', type: 'pronoun', register: 'neutral' },
    'nous': { en: 'we', pron: 'noo', type: 'pronoun', register: 'neutral', note: 'formal/written; spoken French prefers on' },
    'vous': { en: 'you (formal) / you all', pron: 'voo', type: 'pronoun', register: 'formal', note: 'the safe default with strangers, elders, groups' },
    'ils': { en: 'they (masc/mixed)', register: 'neutral', note: 'pronounced exactly like il' },
    'elles': { en: 'they (fem)', register: 'neutral', note: 'pronounced exactly like elle' },
    'on': { en: 'one / we (informal)', register: 'informal', note: 'takes a 3rd-singular verb' },
    'moi': { en: 'me', register: 'neutral' },
    // être + avoir
    'suis': { en: 'I am', pron: 'swee', type: 'verb', register: 'neutral',
        label: '1ST PERSON SINGULAR PRESENT OF ÊTRE',
        base: { form: 'être', en: 'to be' },
        conj: [
            { label: '1st person sing.', form: 'je suis' },
            { label: '2nd person sing.', form: 'tu es' },
            { label: '3rd person sing.', form: 'il/elle est' },
            { label: '1st person plural', form: 'nous sommes' },
            { label: '2nd person plural', form: 'vous êtes' },
            { label: '3rd person plural', form: 'ils/elles sont' },
        ],
        detail: 'Être is one of the two most important French verbs. It is IRREGULAR — the forms must be memorised. Je suis = "I am". Notice that suis is nothing like the infinitive être — this is normal for irregular verbs. Use être for identity, nationality, profession (no article!), and time.' },
    
    'es': { en: 'you are', pron: 'eh', type: 'verb', register: 'informal',
        label: '2ND PERSON SINGULAR PRESENT OF ÊTRE',
        base: { form: 'être', en: 'to be' },
        detail: 'Tu es = "you are" (informal). Only use with friends, family and children. The -s is silent but must be written.' },
    
    'est': { en: 'is', pron: 'eh', type: 'verb', register: 'neutral',
        label: '3RD PERSON SINGULAR PRESENT OF ÊTRE',
        base: { form: 'être', en: 'to be' },
        detail: 'Il est / Elle est = "he is / she is". Also used impersonally for time: il est trois heures. And with adjectives describing state: elle est fatiguée.' },
    
    'sommes': { en: 'we are', pron: 'som', type: 'verb', register: 'neutral',
        label: '1ST PERSON PLURAL PRESENT OF ÊTRE',
        base: { form: 'être', en: 'to be' },
        conj: [
            { label: '1st person sing.', form: 'je suis' },
            { label: '2nd person sing.', form: 'tu es' },
            { label: '3rd person sing.', form: 'il/elle est' },
            { label: '1st person plural', form: 'nous sommes' },
            { label: '2nd person plural', form: 'vous êtes' },
            { label: '3rd person plural', form: 'ils/elles sont' },
        ],
        detail: 'Nous sommes = "we are". The formal/written "we" — spoken French prefers on est. Rhymes with "home".' },
    
    'êtes': { en: 'you are (formal/plural)', pron: 'ett', type: 'verb', register: 'formal',
        label: '2ND PERSON PLURAL PRESENT OF ÊTRE',
        base: { form: 'être', en: 'to be' },
        detail: 'Vous êtes = "you are" (formal singular OR plural). The only être form with a pronounced consonant cluster — "ett" rhymes with "bet".' },
    
    'sont': { en: 'they are', pron: 'sohn', type: 'verb', register: 'neutral',
        label: '3RD PERSON PLURAL PRESENT OF ÊTRE',
        base: { form: 'être', en: 'to be' },
        conj: [
            { label: '1st person sing.', form: 'je suis' },
            { label: '2nd person sing.', form: 'tu es' },
            { label: '3rd person sing.', form: 'il/elle est' },
            { label: '1st person plural', form: 'nous sommes' },
            { label: '2nd person plural', form: 'vous êtes' },
            { label: '3rd person plural', form: 'ils/elles sont' },
        ],
        detail: 'Ils sont / Elles sont = "they are". The nasal on sounds like "song" without the hard g — it does NOT rhyme with "dont".' },
    
    'ai': { en: 'I have', pron: 'ay', type: 'verb', register: 'neutral',
        label: '1ST PERSON SINGULAR PRESENT OF AVOIR (ELIDED)',
        base: { form: 'avoir', en: 'to have' },
        conj: [
            { label: '1st person sing.', form: 'j\u2019ai' },
            { label: '2nd person sing.', form: 'tu as' },
            { label: '3rd person sing.', form: 'il/elle a' },
            { label: '1st person plural', form: 'nous avons' },
            { label: '2nd person plural', form: 'vous avez' },
            { label: '3rd person plural', form: 'ils/elles ont' },
        ],
        detail: 'This is the elided form of "je" + "ai". The apostrophe replaces the vowel "e" in "je" because the verb "ai" begins with a vowel, which is required in French to avoid hiatus. It is the 1st person singular present tense of "avoir" (to have).' },
    
    'as': { en: 'you have', pron: 'ah', type: 'verb', register: 'informal',
        label: '2ND PERSON SINGULAR PRESENT OF AVOIR',
        base: { form: 'avoir', en: 'to have' },
        detail: 'Tu as = "you have" (informal). Pronounced exactly like il/elle a — context tells you which.' },
    
    'a': { en: 'has', pron: 'ah', type: 'verb', register: 'neutral',
        label: '3RD PERSON SINGULAR PRESENT OF AVOIR',
        base: { form: 'avoir', en: 'to have' },
        conj: [
            { label: '1st person sing.', form: 'j\u2019ai' },
            { label: '2nd person sing.', form: 'tu as' },
            { label: '3rd person sing.', form: 'il/elle a' },
            { label: '1st person plural', form: 'nous avons' },
            { label: '2nd person plural', form: 'vous avez' },
            { label: '3rd person plural', form: 'ils/elles ont' },
        ],
        detail: 'Il a / Elle a = "he has / she has". Pronounced "ah" — the same as tu as. But ils ont (they have) sounds totally different: "ohn" (nasal). Mixing il a and ils ont will confuse the examiner.' },
    
    'avons': { en: 'have (nous avons)', register: 'neutral' },
    'avez': { en: 'have (vous avez)', register: 'formal' },
    'ont': { en: 'they have', pron: 'ohn', type: 'verb', register: 'neutral',
        label: '3RD PERSON PLURAL PRESENT OF AVOIR',
        base: { form: 'avoir', en: 'to have' },
        conj: [
            { label: '1st person sing.', form: 'j\u2019ai' },
            { label: '2nd person sing.', form: 'tu as' },
            { label: '3rd person sing.', form: 'il/elle a' },
            { label: '1st person plural', form: 'nous avons' },
            { label: '2nd person plural', form: 'vous avez' },
            { label: '3rd person plural', form: 'ils/elles ont' },
        ],
        detail: 'Ils ont / Elles ont = "they have". The nasal on sounds like "ohn". Trap: il a ("eel-AH") vs ils ont ("eel-OHN") — completely different sounds for nearly the same spelling.' },
    
    'être': { en: 'to be', register: 'neutral' },
    'avoir': { en: 'to have', register: 'neutral', note: 'also used for age and body states: j\u2019ai 20 ans, j\u2019ai faim' },
    // negation & questions
    'ne': { en: 'not — first half of the sandwich', register: 'neutral', note: 'ne + verb + pas' },
    'pas': { en: 'not — second half of the sandwich', register: 'neutral' },
    'est-ce que': { en: 'question marker', register: 'neutral', note: 'safe in every register' },
    'est-ce': { en: 'is it (start of est-ce que)', register: 'neutral' },
    'qu\u2019': { en: 'that / what (elided before a vowel)', register: 'neutral' },
    'que': { en: 'that / what', register: 'neutral' },
    'qui': { en: 'who', register: 'neutral' },
    'quoi': { en: 'what', register: 'neutral' },
    'où': { en: 'where', pron: 'oo', type: 'adverb', register: 'neutral', note: 'accent required — ou without it means or' },
    'quand': { en: 'when', pron: 'kahn', type: 'adverb', register: 'neutral' },
    'comment': { en: 'how', pron: 'koh-MAHN', type: 'adverb', register: 'neutral' },
    'pourquoi': { en: 'why', pron: 'poor-KWAH', type: 'adverb', register: 'neutral', note: 'porque = because (one word, no accent)' },
    'parce que': { en: 'because', register: 'neutral' },
    'combien': { en: 'how much / how many', pron: 'kohn-BYAN', type: 'adverb', register: 'neutral' },
    'quel': { en: 'which / what (masc)', gender: 'masculine', register: 'neutral' },
    'quelle': { en: 'which / what (fem)', gender: 'feminine', register: 'neutral' },
    // function words
    'et': { en: 'and', register: 'neutral' },
    'ou': { en: 'or', register: 'neutral', note: 'où with an accent means where' },
    'mais': { en: 'but', register: 'neutral' },
    'avec': { en: 'with', register: 'neutral' },
    'dans': { en: 'in / inside', register: 'neutral' },
    'à': { en: 'at / to / till', register: 'neutral' },
    'de': { en: 'of / from', register: 'neutral' },
    'du': { en: 'of the / some (masc) — de + le', register: 'neutral' },
    'de la': { en: 'of the / some (fem)', register: 'neutral' },
    'des': { en: 'some (plural) / of the (plural)', register: 'neutral', note: 'becomes de in negative sentences' },
    'au': { en: 'to the / at the (masc) — à + le', register: 'neutral' },
    'à la': { en: 'to the (fem)', register: 'neutral' },
    'aux': { en: 'to the (plural) — à + les', register: 'neutral' },
    'le': { en: 'the (masculine)', register: 'neutral' },
    'la': { en: 'the (feminine)', register: 'neutral' },
    'les': { en: 'the (plural)', register: 'neutral' },
    'l\u2019': { en: 'the (before a vowel)', register: 'neutral' },
    'un': { en: 'a (masculine)', gender: 'masculine', register: 'neutral' },
    'une': { en: 'a (feminine)', gender: 'feminine', register: 'neutral' },
    'mon': { en: 'my (masculine object)', register: 'neutral', note: 'agrees with the OBJECT owned, not the owner' },
    'ma': { en: 'my (feminine object)', register: 'neutral', note: 'mon amie — masculine form before a vowel' },
    'mes': { en: 'my (plural object)', register: 'neutral' },
    'ton': { en: 'your (masc object)', register: 'informal' },
    'ta': { en: 'your (fem object)', register: 'informal' },
    'tes': { en: 'your (plural object)', register: 'informal' },
    'son': { en: 'his / her (masc object)', register: 'neutral', note: 'agrees with the OBJECT: sa sœur = his sister' },
    'sa': { en: 'his / her (fem object)', register: 'neutral' },
    'ses': { en: 'his / her (plural object)', register: 'neutral' },
    'notre': { en: 'our (sing object)', register: 'neutral' },
    'nos': { en: 'our (plural object)', register: 'neutral' },
    'votre': { en: 'your (sing object, formal)', register: 'formal' },
    'vos': { en: 'your (plural object)', register: 'formal' },
    'leur': { en: 'their (sing object)', register: 'neutral' },
    'leurs': { en: 'their (plural object)', register: 'neutral' },
    'c\u2019est': { en: 'it is / this is', pron: 'say', type: 'phrase', register: 'neutral' },
    'ce n\u2019est pas': { en: 'it is not / this is not', register: 'neutral' },
    'il y a': { en: 'there is / there are', pron: 'eel yee AH', type: 'phrase', register: 'neutral' },
    'je voudrais': { en: 'I would like', pron: 'zhuh voo-DREH', type: 'phrase', register: 'neutral', note: 'polite — the standard way to order/ask' },
    'je peux': { en: 'I can', register: 'neutral' },
    'je dois': { en: 'I must / I have to', register: 'neutral' },
    'je vais': { en: 'I go / I am going', register: 'neutral' },
    'j\u2019ai': { en: 'I have', pron: 'zhay', type: 'phrase', register: 'neutral' },
    'je suis': { en: 'I am', pron: 'zhuh SWEE', type: 'phrase', register: 'neutral' },
    'je ne suis pas': { en: 'I am not', register: 'neutral' },
    'je n\u2019ai pas': { en: 'I don\u2019t have', register: 'neutral', note: 'un/une/des become de in negatives' },
    // time & frequency basics
    'aujourd\u2019hui': { en: 'today', register: 'neutral' },
    'demain': { en: 'tomorrow', gender: 'masculine', register: 'neutral' },
    'hier': { en: 'yesterday', register: 'neutral', gender: 'masculine' },
    'matin': { en: 'morning', gender: 'masculine', register: 'neutral' },
    'soir': { en: 'evening', gender: 'masculine', register: 'neutral' },
    'maintenant': { en: 'now', register: 'neutral' },
    'toujours': { en: 'always', register: 'neutral' },
    'souvent': { en: 'often', register: 'neutral' },
    'parfois': { en: 'sometimes', register: 'neutral' },
    'jamais': { en: 'never', register: 'neutral', note: 'ne … jamais — keep the ne' },
    'bien': { en: 'well / fine', register: 'neutral', note: 'bien = well vs bon = good' },
    'très': { en: 'very', register: 'neutral' },
    'mal': { en: 'badly / unwell', register: 'neutral', note: 'mal = badly vs mauvais = bad' },
    'pas mal': { en: 'not bad', register: 'informal' },
    // greetings (recap from the first lecture)
    'bonjour': { en: 'hello / good morning (until ~6pm)', pron: 'bohn-ZHOOR', type: 'phrase', register: 'neutral', note: 'always when entering a shop' },
    'bonsoir': { en: 'good evening (from ~6pm)', register: 'neutral' },
    'salut': { en: 'hi / bye', register: 'informal', note: 'friends & family only' },
    'au revoir': { en: 'goodbye', register: 'neutral' },
    'à bientôt': { en: 'see you soon', register: 'neutral' },
    'merci': { en: 'thank you', pron: 'mair-SEE', type: 'phrase', register: 'neutral' },
    's\u2019il vous plaît': { en: 'please', register: 'formal' },
    'je m\u2019appelle': { en: 'my name is (lit. I call myself)', pron: 'zhuh mah-PEL', type: 'phrase', register: 'neutral', note: 'from the reflexive verb s\u2019appeler' },
    'ça va': { en: 'how are you / I\u2019m fine', pron: 'sah VAH', type: 'phrase', register: 'informal' },
    'comment allez-vous': { en: 'how are you (formal)', register: 'formal' },
    'oui': { en: 'yes', pron: 'wee', type: 'adverb', register: 'neutral' },
    'non': { en: 'no', pron: 'nohn', type: 'adverb', register: 'neutral' },
    // ── common verbs ──
    'parler': { en: 'to speak', register: 'neutral' },
    'parles': { en: 'speak (tu form)', register: 'neutral' },
    'mange': { en: 'eat(s)', pron: 'mahnzh', type: 'verb', register: 'neutral', note: 'from manger' },
    'manges': { en: 'eat (tu form)', register: 'neutral' },
    'bois': { en: 'drink (je/tu form of boire)', register: 'neutral' },
    'boit': { en: 'drinks (il/elle form of boire)', register: 'neutral' },
    'habite': { en: 'live(s)', pron: 'ah-BEET', type: 'verb', register: 'neutral', note: 'from habiter' },
    'travailles': { en: 'work (tu form)', register: 'neutral' },
    'travaille': { en: 'work(s) (je/il form)', register: 'neutral' },
    'travaillons': { en: 'work (nous form)', register: 'neutral' },
    'travaillez': { en: 'work (vous form)', register: 'neutral' },
    'étudie': { en: 'study/studies', register: 'neutral' },
    'apprends': { en: 'learn/learns', register: 'neutral' },
    'aime': { en: 'like / love', pron: 'em', type: 'verb', register: 'neutral', note: 'j\u2019aime le fromage — likes use the definite article' },
    'adapte': { en: 'adapt(s)', register: 'neutral' },
    'regarde': { en: 'watch / look at', pron: 'ruh-GARD', type: 'verb', register: 'neutral' },
    'écoute': { en: 'listen(s) to', register: 'neutral' },
    'veux': { en: 'want (tu form of vouloir)', register: 'neutral' },
    'veut': { en: 'want(s) (il/elle form of vouloir)', register: 'neutral' },
    'peux': { en: 'can (je/tu form of pouvoir)', register: 'neutral' },
    'peut': { en: 'can (il/elle form of pouvoir)', register: 'neutral' },
    'dois': { en: 'must (je/tu form of devoir)', register: 'neutral' },
    'doit': { en: 'must (il/elle form of devoir)', register: 'neutral' },
    'fais': { en: 'do/make (je/tu form of faire)', register: 'neutral' },
    'fait': { en: 'does/makes (il/elle form of faire)', register: 'neutral' },
    'vais': { en: 'go (je form of aller)', register: 'neutral' },
    'vas': { en: 'go (tu form of aller)', register: 'neutral' },
    'connais': { en: 'know (a person/place)', register: 'neutral', note: 'connaître = know people/places vs savoir = know facts' },
    'sais': { en: 'know (a fact — from savoir)', register: 'neutral' },
    'vois': { en: 'see (je form of voir)', register: 'neutral' },
    'viens': { en: 'come (je/tu form of venir)', register: 'neutral' },
    'vient': { en: 'comes (il/elle form of venir)', register: 'neutral' },
    'veux-tu': { en: 'do you want', register: 'informal' },
    'peux-tu': { en: 'can you', register: 'informal' },
    // ── common adjectives ──
    'bonne': { en: 'good (fem)', gender: 'feminine', register: 'neutral' },
    'mauvais': { en: 'bad', gender: 'masculine', register: 'neutral' },
    'grande': { en: 'big / tall (fem)', gender: 'feminine', register: 'neutral' },
    'petits': { en: 'small (masc pl)', register: 'neutral' },
    'content': { en: 'happy (masc)', register: 'neutral', note: 'feminine: contente' },
    'contente': { en: 'happy (fem)', gender: 'feminine', register: 'neutral' },
    'fatigué': { en: 'tired (masc)', register: 'neutral', note: 'feminine: fatiguée' },
    'fatiguée': { en: 'tired (fem)', gender: 'feminine', register: 'neutral' },
    'facile': { en: 'easy', register: 'neutral' },
    'difficile': { en: 'difficult / hard', register: 'neutral' },
    'important': { en: 'important', gender: 'masculine', register: 'neutral' },
    'préféré': { en: 'favourite (masc)', register: 'neutral', note: 'feminine: préférée' },
    // ── common nouns ──
    'livre': { en: 'book', gender: 'masculine', plural: 'livres', register: 'neutral' },
    'table': { en: 'table', gender: 'feminine', register: 'neutral' },
    'porte': { en: 'door', gender: 'feminine', register: 'neutral' },
    'temps': { en: 'time / weather', gender: 'masculine', register: 'neutral', note: 'combien de temps = how long; quel temps = what weather' },
    'jour': { en: 'day', gender: 'masculine', register: 'neutral' },
    'maison': { en: 'house / home', gender: 'feminine', register: 'neutral', note: 'à la maison = at home' },
    'travail': { en: 'work (noun)', gender: 'masculine', register: 'neutral' },
    'professeur': { en: 'teacher (masc)', gender: 'masculine', register: 'neutral' },
    'étudiant': { en: 'student (masc)', gender: 'masculine', register: 'neutral', note: 'feminine: étudiante' },
    'étudiante': { en: 'student (fem)', gender: 'feminine', register: 'neutral' },
    'école': { en: 'school', gender: 'feminine', register: 'neutral', note: 'vowel start → l\u2019école' },
    'question': { en: 'question', gender: 'feminine', register: 'neutral' },
    'questions': { en: 'questions (plural)', gender: 'feminine', register: 'neutral' },
    'chose': { en: 'thing', gender: 'feminine', register: 'neutral' },
    'rien': { en: 'nothing', register: 'neutral', note: 'ne…rien = nothing' },
    'quelqu\u2019un': { en: 'somebody', register: 'neutral' },
    'accord': { en: 'agreement', gender: 'masculine', register: 'neutral' },
    'français': { en: 'French / Frenchman', gender: 'masculine', register: 'neutral' },
    'française': { en: 'French / Frenchwoman', gender: 'feminine', register: 'neutral' },
    'langue': { en: 'language / tongue', gender: 'feminine', register: 'neutral' },
    'mot': { en: 'word', gender: 'masculine', plural: 'mots', register: 'neutral' },
    'nombre': { en: 'number', gender: 'masculine', register: 'neutral' },
    'personne': { en: 'person / nobody', gender: 'feminine', register: 'neutral', note: 'ne…personne = nobody' },
    // ── common adverbs & expressions ──
    'aussi': { en: 'also / too', register: 'neutral' },
    'ensemble': { en: 'together', register: 'neutral' },
    'beaucoup': { en: 'a lot / very much', register: 'neutral' },
    'un peu': { en: 'a little', register: 'neutral' },
    'trop': { en: 'too much / too many', register: 'neutral', note: 'final p silent' },
    'assez': { en: 'enough / quite', register: 'neutral' },
    'vite': { en: 'fast / quickly', register: 'neutral' },
    'lentement': { en: 'slowly', register: 'neutral' },
    'ici': { en: 'here', register: 'neutral' },
    'là': { en: 'there', register: 'neutral' },
    'partout': { en: 'everywhere', register: 'neutral' },
    'encore': { en: 'still / again', register: 'neutral' },
    'déjà': { en: 'already', register: 'neutral' },
    'bientôt': { en: 'soon', register: 'neutral' },
    'ensuite': { en: 'then / next', register: 'neutral' },
    'd\u2019abord': { en: 'first', register: 'neutral' },
    'après': { en: 'after / afterwards', register: 'neutral' },
    'avant': { en: 'before', register: 'neutral' },
    'enfin': { en: 'finally', register: 'neutral' },
    'vers': { en: 'around (a time) / towards', register: 'neutral' },
    'd\u2019habitude': { en: 'usually', register: 'neutral' },
    'tout le monde': { en: 'everybody', register: 'neutral' },
    // ── key adjectives with masc/fem pairs ──
    'bon': { en: 'good', pron: 'bohn', type: 'adjective', gender: 'masculine', register: 'neutral',
        masc: { word: 'bon', en: 'good (for a man/boy) — nasal n' },
        fem: { word: 'bonne', en: 'good (for a woman/girl) — n fully pronounced' },
        detail: 'The feminine adds -e, making the n a full consonant: bon = nasal "bohn" vs bonne = "bon" with a clear n.' },
    'grand': { en: 'tall / big', pron: 'GRAHN', type: 'adjective', gender: 'masculine', register: 'neutral',
        masc: { word: 'grand', en: 'tall (masc) — d silent' },
        fem: { word: 'grande', en: 'tall (fem) — d pronounced' },
        detail: 'The masculine final d is SILENT. In the feminine, the added -e makes the d pronounce: grand = "GRAHN" vs grande = "GRAHND".' },
    'petit': { en: 'small / short', pron: 'puh-TEE', type: 'adjective', gender: 'masculine', register: 'neutral',
        masc: { word: 'petit', en: 'small (masc) — final t silent' },
        fem: { word: 'petite', en: 'small (fem) — final t pronounced' },
        detail: 'The final t is silent in petit but pronounced in petite because the -e opens the syllable: "puh-TEE" vs "puh-TEET".' },
    'gentil': { en: 'kind', pron: 'zhon-TEE', type: 'adjective', gender: 'masculine', register: 'neutral',
        masc: { word: 'gentil', en: 'kind (masc)' },
        fem: { word: 'gentille', en: 'kind (fem) — double l + e' },
        detail: 'Gentil doubles the l in the feminine: gentille. The double ll sounds like a y-glide: "zhon-TEE-yuh".' },
    'gros': { en: 'fat / big', pron: 'GROH', type: 'adjective', gender: 'masculine', register: 'neutral',
        masc: { word: 'gros', en: 'big (masc)' },
        fem: { word: 'grosse', en: 'big (fem) — double s' },
        detail: 'Grosse has a double s which makes the s a clear s sound: gros = "GROH" vs grosse = "GROSS".' },
    'beau': { en: 'beautiful / handsome', pron: 'BOH', type: 'adjective', gender: 'masculine', register: 'neutral',
        masc: { word: 'beau', en: 'handsome (masc)' },
        fem: { word: 'belle', en: 'beautiful (fem) — IRREGULAR!' },
        detail: 'Beau is IRREGULAR: the feminine is belle (not beaue). Before a vowel it becomes bel: un bel homme.' },
    'nouveau': { en: 'new', pron: 'noo-VOH', type: 'adjective', gender: 'masculine', register: 'neutral',
        masc: { word: 'nouveau', en: 'new (masc)' },
        fem: { word: 'nouvelle', en: 'new (fem) — IRREGULAR' },
        detail: 'Nouveau is irregular: feminine is nouvelle. Before a vowel: un nouvel amour.' },

    'c\u2019est-à-dire': { en: 'that is to say (i.e.)', register: 'neutral' },
    'par exemple': { en: 'for example', register: 'neutral' },
    'bien sûr': { en: 'of course', register: 'neutral' },
    'd\u2019accord': { en: 'okay / agreed', register: 'neutral' },
    'pas question': { en: 'no way', register: 'informal' },
    'tout à fait': { en: 'exactly / absolutely', register: 'neutral' },
};
