// Shared glossary for ALL French lectures — function words every lesson reuses.
// Each lecture's own glossary spreads this and adds its specific words, so the
// tap-to-translate toolkit covers common words without duplicating entries.

export const BASE_GLOSSARY: Record<string, import('./frenchLessons').GlossaryEntry> = {
    // pronouns
    'je': { en: 'I', register: 'neutral', note: 'becomes j\u2019 before a vowel: j\u2019ai, j\u2019habite' },
    'tu': { en: 'you', register: 'informal', note: 'friends, family, children — never strangers/elders' },
    'il': { en: 'he / it', register: 'neutral' },
    'elle': { en: 'she / it', register: 'neutral' },
    'nous': { en: 'we', register: 'neutral', note: 'formal/written; spoken French prefers on' },
    'vous': { en: 'you (formal) / you all', register: 'formal', note: 'the safe default with strangers, elders, groups' },
    'ils': { en: 'they (masc/mixed)', register: 'neutral', note: 'pronounced exactly like il' },
    'elles': { en: 'they (fem)', register: 'neutral', note: 'pronounced exactly like elle' },
    'on': { en: 'one / we (informal)', register: 'informal', note: 'takes a 3rd-singular verb' },
    'moi': { en: 'me', register: 'neutral' },
    // être + avoir
    'suis': { en: 'am (je suis)', register: 'neutral' },
    'es': { en: 'are (tu es)', register: 'informal' },
    'est': { en: 'is (il/elle est)', register: 'neutral' },
    'sommes': { en: 'are (nous sommes)', register: 'neutral' },
    'êtes': { en: 'are (vous êtes)', register: 'formal' },
    'sont': { en: 'are (ils/elles sont)', register: 'neutral', note: 'nasal — song without the hard g' },
    'ai': { en: 'have (j\u2019ai)', register: 'neutral' },
    'as': { en: 'have (tu as)', register: 'informal' },
    'a': { en: 'has (il/elle a)', register: 'neutral' },
    'avons': { en: 'have (nous avons)', register: 'neutral' },
    'avez': { en: 'have (vous avez)', register: 'formal' },
    'ont': { en: 'have (ils/elles ont)', register: 'neutral', note: 'nasal — il a vs ils ont sound totally different' },
    'être': { en: 'to be', register: 'neutral' },
    'avoir': { en: 'to have', register: 'neutral', note: 'also used for age and body states: j\u2019ai 20 ans, j\u2019ai faim' },
    // negation & questions
    'ne': { en: 'not — first half of the sandwich', register: 'neutral', note: 'ne + verb + pas' },
    'pas': { en: 'not — second half of the sandwich', register: 'neutral' },
    'est-ce que': { en: 'question marker', register: 'neutral', note: 'safe in every register' },
    'est-ce': { en: 'is it (start of est-ce que)', register: 'neutral' },
    'qu\u2019': { en: 'that / what (elided before a vowel)', register: 'neutral' },
    'que': { en: 'that / what', register: 'neutral' },
    'qui': { en: 'who', register: 'neutral' },
    'quoi': { en: 'what', register: 'neutral' },
    'où': { en: 'where', register: 'neutral', note: 'accent required — ou without it means or' },
    'quand': { en: 'when', register: 'neutral' },
    'comment': { en: 'how', register: 'neutral' },
    'pourquoi': { en: 'why', register: 'neutral', note: 'porque = because (one word, no accent)' },
    'parce que': { en: 'because', register: 'neutral' },
    'combien': { en: 'how much / how many', register: 'neutral' },
    'quel': { en: 'which / what (masc)', gender: 'masculine', register: 'neutral' },
    'quelle': { en: 'which / what (fem)', gender: 'feminine', register: 'neutral' },
    // function words
    'et': { en: 'and', register: 'neutral' },
    'ou': { en: 'or', register: 'neutral', note: 'où with an accent means where' },
    'mais': { en: 'but', register: 'neutral' },
    'avec': { en: 'with', register: 'neutral' },
    'dans': { en: 'in / inside', register: 'neutral' },
    'à': { en: 'at / to / till', register: 'neutral' },
    'de': { en: 'of / from', register: 'neutral' },
    'du': { en: 'of the / some (masc) — de + le', register: 'neutral' },
    'de la': { en: 'of the / some (fem)', register: 'neutral' },
    'des': { en: 'some (plural) / of the (plural)', register: 'neutral', note: 'becomes de in negative sentences' },
    'au': { en: 'to the / at the (masc) — à + le', register: 'neutral' },
    'à la': { en: 'to the (fem)', register: 'neutral' },
    'aux': { en: 'to the (plural) — à + les', register: 'neutral' },
    'le': { en: 'the (masculine)', register: 'neutral' },
    'la': { en: 'the (feminine)', register: 'neutral' },
    'les': { en: 'the (plural)', register: 'neutral' },
    'l\u2019': { en: 'the (before a vowel)', register: 'neutral' },
    'un': { en: 'a (masculine)', gender: 'masculine', register: 'neutral' },
    'une': { en: 'a (feminine)', gender: 'feminine', register: 'neutral' },
    'mon': { en: 'my (masculine object)', register: 'neutral', note: 'agrees with the OBJECT owned, not the owner' },
    'ma': { en: 'my (feminine object)', register: 'neutral', note: 'mon amie — masculine form before a vowel' },
    'mes': { en: 'my (plural object)', register: 'neutral' },
    'ton': { en: 'your (masc object)', register: 'informal' },
    'ta': { en: 'your (fem object)', register: 'informal' },
    'tes': { en: 'your (plural object)', register: 'informal' },
    'son': { en: 'his / her (masc object)', register: 'neutral', note: 'agrees with the OBJECT: sa sœur = his sister' },
    'sa': { en: 'his / her (fem object)', register: 'neutral' },
    'ses': { en: 'his / her (plural object)', register: 'neutral' },
    'notre': { en: 'our (sing object)', register: 'neutral' },
    'nos': { en: 'our (plural object)', register: 'neutral' },
    'votre': { en: 'your (sing object, formal)', register: 'formal' },
    'vos': { en: 'your (plural object)', register: 'formal' },
    'leur': { en: 'their (sing object)', register: 'neutral' },
    'leurs': { en: 'their (plural object)', register: 'neutral' },
    'c\u2019est': { en: 'it is / this is', register: 'neutral' },
    'ce n\u2019est pas': { en: 'it is not / this is not', register: 'neutral' },
    'il y a': { en: 'there is / there are', register: 'neutral' },
    'je voudrais': { en: 'I would like', register: 'neutral', note: 'polite — the standard way to order/ask' },
    'je peux': { en: 'I can', register: 'neutral' },
    'je dois': { en: 'I must / I have to', register: 'neutral' },
    'je vais': { en: 'I go / I am going', register: 'neutral' },
    'j\u2019ai': { en: 'I have', register: 'neutral' },
    'je suis': { en: 'I am', register: 'neutral' },
    'je ne suis pas': { en: 'I am not', register: 'neutral' },
    'je n\u2019ai pas': { en: 'I don\u2019t have', register: 'neutral', note: 'un/une/des become de in negatives' },
    // time & frequency basics
    'aujourd\u2019hui': { en: 'today', register: 'neutral' },
    'demain': { en: 'tomorrow', gender: 'masculine', register: 'neutral' },
    'hier': { en: 'yesterday', register: 'neutral', gender: 'masculine' },
    'matin': { en: 'morning', gender: 'masculine', register: 'neutral' },
    'soir': { en: 'evening', gender: 'masculine', register: 'neutral' },
    'maintenant': { en: 'now', register: 'neutral' },
    'toujours': { en: 'always', register: 'neutral' },
    'souvent': { en: 'often', register: 'neutral' },
    'parfois': { en: 'sometimes', register: 'neutral' },
    'jamais': { en: 'never', register: 'neutral', note: 'ne … jamais — keep the ne' },
    'bien': { en: 'well / fine', register: 'neutral', note: 'bien = well vs bon = good' },
    'très': { en: 'very', register: 'neutral' },
    'mal': { en: 'badly / unwell', register: 'neutral', note: 'mal = badly vs mauvais = bad' },
    'pas mal': { en: 'not bad', register: 'informal' },
    // greetings (recap from the first lecture)
    'bonjour': { en: 'hello / good morning (until ~6pm)', register: 'neutral', note: 'always when entering a shop' },
    'bonsoir': { en: 'good evening (from ~6pm)', register: 'neutral' },
    'salut': { en: 'hi / bye', register: 'informal', note: 'friends & family only' },
    'au revoir': { en: 'goodbye', register: 'neutral' },
    'à bientôt': { en: 'see you soon', register: 'neutral' },
    'merci': { en: 'thank you', register: 'neutral' },
    's\u2019il vous plaît': { en: 'please', register: 'formal' },
    'je m\u2019appelle': { en: 'my name is (lit. I call myself)', register: 'neutral', note: 'from the reflexive verb s\u2019appeler' },
    'ça va': { en: 'how are you / I\u2019m fine (informal)', register: 'informal' },
    'comment allez-vous': { en: 'how are you (formal)', register: 'formal' },
    'oui': { en: 'yes', register: 'neutral' },
    'non': { en: 'no', register: 'neutral' },
};
