// Shared glossary for ALL French lectures — function words every lesson reuses.
// Each lecture's own glossary spreads this and adds its specific words, so the
// tap-to-translate toolkit covers common words without duplicating entries.

export const BASE_GLOSSARY: Record<string, import('./frenchLessons').GlossaryEntry> = {
    // pronouns
    'je': { en: 'I', register: 'neutral', note: 'becomes j\u2019 before a vowel: j\u2019ai, j\u2019habite' },
    'tu': { en: 'you', register: 'informal', note: 'friends, family, children — never strangers/elders' },
    'il': { en: 'he / it', register: 'neutral' },
    'elle': { en: 'she / it', register: 'neutral' },
    'nous': { en: 'we', register: 'neutral', note: 'formal/written; spoken French prefers on' },
    'vous': { en: 'you (formal) / you all', register: 'formal', note: 'the safe default with strangers, elders, groups' },
    'ils': { en: 'they (masc/mixed)', register: 'neutral', note: 'pronounced exactly like il' },
    'elles': { en: 'they (fem)', register: 'neutral', note: 'pronounced exactly like elle' },
    'on': { en: 'one / we (informal)', register: 'informal', note: 'takes a 3rd-singular verb' },
    'moi': { en: 'me', register: 'neutral' },
    // être + avoir
    'suis': { en: 'am (je suis)', register: 'neutral' },
    'es': { en: 'are (tu es)', register: 'informal' },
    'est': { en: 'is (il/elle est)', register: 'neutral' },
    'sommes': { en: 'are (nous sommes)', register: 'neutral' },
    'êtes': { en: 'are (vous êtes)', register: 'formal' },
    'sont': { en: 'are (ils/elles sont)', register: 'neutral', note: 'nasal — song without the hard g' },
    'ai': { en: 'have (j\u2019ai)', register: 'neutral' },
    'as': { en: 'have (tu as)', register: 'informal' },
    'a': { en: 'has (il/elle a)', register: 'neutral' },
    'avons': { en: 'have (nous avons)', register: 'neutral' },
    'avez': { en: 'have (vous avez)', register: 'formal' },
    'ont': { en: 'have (ils/elles ont)', register: 'neutral', note: 'nasal — il a vs ils ont sound totally different' },
    'être': { en: 'to be', register: 'neutral' },
    'avoir': { en: 'to have', register: 'neutral', note: 'also used for age and body states: j\u2019ai 20 ans, j\u2019ai faim' },
    // negation & questions
    'ne': { en: 'not — first half of the sandwich', register: 'neutral', note: 'ne + verb + pas' },
    'pas': { en: 'not — second half of the sandwich', register: 'neutral' },
    'est-ce que': { en: 'question marker', register: 'neutral', note: 'safe in every register' },
    'est-ce': { en: 'is it (start of est-ce que)', register: 'neutral' },
    'qu\u2019': { en: 'that / what (elided before a vowel)', register: 'neutral' },
    'que': { en: 'that / what', register: 'neutral' },
    'qui': { en: 'who', register: 'neutral' },
    'quoi': { en: 'what', register: 'neutral' },
    'où': { en: 'where', register: 'neutral', note: 'accent required — ou without it means or' },
    'quand': { en: 'when', register: 'neutral' },
    'comment': { en: 'how', register: 'neutral' },
    'pourquoi': { en: 'why', register: 'neutral', note: 'porque = because (one word, no accent)' },
    'parce que': { en: 'because', register: 'neutral' },
    'combien': { en: 'how much / how many', register: 'neutral' },
    'quel': { en: 'which / what (masc)', gender: 'masculine', register: 'neutral' },
    'quelle': { en: 'which / what (fem)', gender: 'feminine', register: 'neutral' },
    // function words
    'et': { en: 'and', register: 'neutral' },
    'ou': { en: 'or', register: 'neutral', note: 'où with an accent means where' },
    'mais': { en: 'but', register: 'neutral' },
    'avec': { en: 'with', register: 'neutral' },
    'dans': { en: 'in / inside', register: 'neutral' },
    'à': { en: 'at / to / till', register: 'neutral' },
    'de': { en: 'of / from', register: 'neutral' },
    'du': { en: 'of the / some (masc) — de + le', register: 'neutral' },
    'de la': { en: 'of the / some (fem)', register: 'neutral' },
    'des': { en: 'some (plural) / of the (plural)', register: 'neutral', note: 'becomes de in negative sentences' },
    'au': { en: 'to the / at the (masc) — à + le', register: 'neutral' },
    'à la': { en: 'to the (fem)', register: 'neutral' },
    'aux': { en: 'to the (plural) — à + les', register: 'neutral' },
    'le': { en: 'the (masculine)', register: 'neutral' },
    'la': { en: 'the (feminine)', register: 'neutral' },
    'les': { en: 'the (plural)', register: 'neutral' },
    'l\u2019': { en: 'the (before a vowel)', register: 'neutral' },
    'un': { en: 'a (masculine)', gender: 'masculine', register: 'neutral' },
    'une': { en: 'a (feminine)', gender: 'feminine', register: 'neutral' },
    'mon': { en: 'my (masculine object)', register: 'neutral', note: 'agrees with the OBJECT owned, not the owner' },
    'ma': { en: 'my (feminine object)', register: 'neutral', note: 'mon amie — masculine form before a vowel' },
    'mes': { en: 'my (plural object)', register: 'neutral' },
    'ton': { en: 'your (masc object)', register: 'informal' },
    'ta': { en: 'your (fem object)', register: 'informal' },
    'tes': { en: 'your (plural object)', register: 'informal' },
    'son': { en: 'his / her (masc object)', register: 'neutral', note: 'agrees with the OBJECT: sa sœur = his sister' },
    'sa': { en: 'his / her (fem object)', register: 'neutral' },
    'ses': { en: 'his / her (plural object)', register: 'neutral' },
    'notre': { en: 'our (sing object)', register: 'neutral' },
    'nos': { en: 'our (plural object)', register: 'neutral' },
    'votre': { en: 'your (sing object, formal)', register: 'formal' },
    'vos': { en: 'your (plural object)', register: 'formal' },
    'leur': { en: 'their (sing object)', register: 'neutral' },
    'leurs': { en: 'their (plural object)', register: 'neutral' },
    'c\u2019est': { en: 'it is / this is', register: 'neutral' },
    'ce n\u2019est pas': { en: 'it is not / this is not', register: 'neutral' },
    'il y a': { en: 'there is / there are', register: 'neutral' },
    'je voudrais': { en: 'I would like', register: 'neutral', note: 'polite — the standard way to order/ask' },
    'je peux': { en: 'I can', register: 'neutral' },
    'je dois': { en: 'I must / I have to', register: 'neutral' },
    'je vais': { en: 'I go / I am going', register: 'neutral' },
    'j\u2019ai': { en: 'I have', register: 'neutral' },
    'je suis': { en: 'I am', register: 'neutral' },
    'je ne suis pas': { en: 'I am not', register: 'neutral' },
    'je n\u2019ai pas': { en: 'I don\u2019t have', register: 'neutral', note: 'un/une/des become de in negatives' },
    // time & frequency basics
    'aujourd\u2019hui': { en: 'today', register: 'neutral' },
    'demain': { en: 'tomorrow', gender: 'masculine', register: 'neutral' },
    'hier': { en: 'yesterday', register: 'neutral', gender: 'masculine' },
    'matin': { en: 'morning', gender: 'masculine', register: 'neutral' },
    'soir': { en: 'evening', gender: 'masculine', register: 'neutral' },
    'maintenant': { en: 'now', register: 'neutral' },
    'toujours': { en: 'always', register: 'neutral' },
    'souvent': { en: 'often', register: 'neutral' },
    'parfois': { en: 'sometimes', register: 'neutral' },
    'jamais': { en: 'never', register: 'neutral', note: 'ne … jamais — keep the ne' },
    'bien': { en: 'well / fine', register: 'neutral', note: 'bien = well vs bon = good' },
    'très': { en: 'very', register: 'neutral' },
    'mal': { en: 'badly / unwell', register: 'neutral', note: 'mal = badly vs mauvais = bad' },
    'pas mal': { en: 'not bad', register: 'informal' },
    // greetings (recap from the first lecture)
    'bonjour': { en: 'hello / good morning (until ~6pm)', register: 'neutral', note: 'always when entering a shop' },
    'bonsoir': { en: 'good evening (from ~6pm)', register: 'neutral' },
    'salut': { en: 'hi / bye', register: 'informal', note: 'friends & family only' },
    'au revoir': { en: 'goodbye', register: 'neutral' },
    'à bientôt': { en: 'see you soon', register: 'neutral' },
    'merci': { en: 'thank you', register: 'neutral' },
    's\u2019il vous plaît': { en: 'please', register: 'formal' },
    'je m\u2019appelle': { en: 'my name is (lit. I call myself)', register: 'neutral', note: 'from the reflexive verb s\u2019appeler' },
    'ça va': { en: 'how are you / I\u2019m fine (informal)', register: 'informal' },
    'comment allez-vous': { en: 'how are you (formal)', register: 'formal' },
    'oui': { en: 'yes', register: 'neutral' },
    'non': { en: 'no', register: 'neutral' },
    // ── common verbs ──
    'parler': { en: 'to speak', register: 'neutral' },
    'parles': { en: 'speak (tu form)', register: 'neutral' },
    'mange': { en: 'eat(s)', register: 'neutral' },
    'manges': { en: 'eat (tu form)', register: 'neutral' },
    'bois': { en: 'drink (je/tu form of boire)', register: 'neutral' },
    'boit': { en: 'drinks (il/elle form of boire)', register: 'neutral' },
    'habite': { en: 'live(s) (from habiter)', register: 'neutral' },
    'travailles': { en: 'work (tu form)', register: 'neutral' },
    'travaille': { en: 'work(s) (je/il form)', register: 'neutral' },
    'travaillons': { en: 'work (nous form)', register: 'neutral' },
    'travaillez': { en: 'work (vous form)', register: 'neutral' },
    'étudie': { en: 'study/studies', register: 'neutral' },
    'apprends': { en: 'learn/learns', register: 'neutral' },
    'aime': { en: 'like/love(s)', register: 'neutral' },
    'adapte': { en: 'adapt(s)', register: 'neutral' },
    'regarde': { en: 'watch(es)', register: 'neutral' },
    'écoute': { en: 'listen(s) to', register: 'neutral' },
    'veux': { en: 'want (tu form of vouloir)', register: 'neutral' },
    'veut': { en: 'want(s) (il/elle form of vouloir)', register: 'neutral' },
    'peux': { en: 'can (je/tu form of pouvoir)', register: 'neutral' },
    'peut': { en: 'can (il/elle form of pouvoir)', register: 'neutral' },
    'dois': { en: 'must (je/tu form of devoir)', register: 'neutral' },
    'doit': { en: 'must (il/elle form of devoir)', register: 'neutral' },
    'fais': { en: 'do/make (je/tu form of faire)', register: 'neutral' },
    'fait': { en: 'does/makes (il/elle form of faire)', register: 'neutral' },
    'vais': { en: 'go (je form of aller)', register: 'neutral' },
    'vas': { en: 'go (tu form of aller)', register: 'neutral' },
    'connais': { en: 'know (a person/place)', register: 'neutral', note: 'connaître = know people/places vs savoir = know facts' },
    'sais': { en: 'know (a fact — from savoir)', register: 'neutral' },
    'vois': { en: 'see (je form of voir)', register: 'neutral' },
    'viens': { en: 'come (je/tu form of venir)', register: 'neutral' },
    'vient': { en: 'comes (il/elle form of venir)', register: 'neutral' },
    'veux-tu': { en: 'do you want', register: 'informal' },
    'peux-tu': { en: 'can you', register: 'informal' },
    // ── common adjectives ──
    'bonne': { en: 'good (fem)', gender: 'feminine', register: 'neutral' },
    'mauvais': { en: 'bad', gender: 'masculine', register: 'neutral' },
    'grande': { en: 'big / tall (fem)', gender: 'feminine', register: 'neutral' },
    'petits': { en: 'small (masc pl)', register: 'neutral' },
    'content': { en: 'happy (masc)', register: 'neutral', note: 'feminine: contente' },
    'contente': { en: 'happy (fem)', gender: 'feminine', register: 'neutral' },
    'fatigué': { en: 'tired (masc)', register: 'neutral', note: 'feminine: fatiguée' },
    'fatiguée': { en: 'tired (fem)', gender: 'feminine', register: 'neutral' },
    'facile': { en: 'easy', register: 'neutral' },
    'difficile': { en: 'difficult / hard', register: 'neutral' },
    'important': { en: 'important', gender: 'masculine', register: 'neutral' },
    'préféré': { en: 'favourite (masc)', register: 'neutral', note: 'feminine: préférée' },
    // ── common nouns ──
    'livre': { en: 'book', gender: 'masculine', plural: 'livres', register: 'neutral' },
    'table': { en: 'table', gender: 'feminine', register: 'neutral' },
    'porte': { en: 'door', gender: 'feminine', register: 'neutral' },
    'temps': { en: 'time / weather', gender: 'masculine', register: 'neutral', note: 'combien de temps = how long; quel temps = what weather' },
    'jour': { en: 'day', gender: 'masculine', register: 'neutral' },
    'maison': { en: 'house / home', gender: 'feminine', register: 'neutral', note: 'à la maison = at home' },
    'travail': { en: 'work (noun)', gender: 'masculine', register: 'neutral' },
    'professeur': { en: 'teacher (masc)', gender: 'masculine', register: 'neutral' },
    'étudiant': { en: 'student (masc)', gender: 'masculine', register: 'neutral', note: 'feminine: étudiante' },
    'étudiante': { en: 'student (fem)', gender: 'feminine', register: 'neutral' },
    'école': { en: 'school', gender: 'feminine', register: 'neutral', note: 'vowel start → l\u2019école' },
    'question': { en: 'question', gender: 'feminine', register: 'neutral' },
    'questions': { en: 'questions (plural)', gender: 'feminine', register: 'neutral' },
    'chose': { en: 'thing', gender: 'feminine', register: 'neutral' },
    'rien': { en: 'nothing', register: 'neutral', note: 'ne…rien = nothing' },
    'quelqu\u2019un': { en: 'somebody', register: 'neutral' },
    'accord': { en: 'agreement', gender: 'masculine', register: 'neutral' },
    'français': { en: 'French / Frenchman', gender: 'masculine', register: 'neutral' },
    'française': { en: 'French / Frenchwoman', gender: 'feminine', register: 'neutral' },
    'langue': { en: 'language / tongue', gender: 'feminine', register: 'neutral' },
    'mot': { en: 'word', gender: 'masculine', plural: 'mots', register: 'neutral' },
    'nombre': { en: 'number', gender: 'masculine', register: 'neutral' },
    'personne': { en: 'person / nobody', gender: 'feminine', register: 'neutral', note: 'ne…personne = nobody' },
    // ── common adverbs & expressions ──
    'aussi': { en: 'also / too', register: 'neutral' },
    'ensemble': { en: 'together', register: 'neutral' },
    'beaucoup': { en: 'a lot / very much', register: 'neutral' },
    'un peu': { en: 'a little', register: 'neutral' },
    'trop': { en: 'too much / too many', register: 'neutral', note: 'final p silent' },
    'assez': { en: 'enough / quite', register: 'neutral' },
    'vite': { en: 'fast / quickly', register: 'neutral' },
    'lentement': { en: 'slowly', register: 'neutral' },
    'ici': { en: 'here', register: 'neutral' },
    'là': { en: 'there', register: 'neutral' },
    'partout': { en: 'everywhere', register: 'neutral' },
    'encore': { en: 'still / again', register: 'neutral' },
    'déjà': { en: 'already', register: 'neutral' },
    'bientôt': { en: 'soon', register: 'neutral' },
    'ensuite': { en: 'then / next', register: 'neutral' },
    'd\u2019abord': { en: 'first', register: 'neutral' },
    'après': { en: 'after / afterwards', register: 'neutral' },
    'avant': { en: 'before', register: 'neutral' },
    'enfin': { en: 'finally', register: 'neutral' },
    'vers': { en: 'around (a time) / towards', register: 'neutral' },
    'd\u2019habitude': { en: 'usually', register: 'neutral' },
    'tout le monde': { en: 'everybody', register: 'neutral' },
    'c\u2019est-à-dire': { en: 'that is to say (i.e.)', register: 'neutral' },
    'par exemple': { en: 'for example', register: 'neutral' },
    'bien sûr': { en: 'of course', register: 'neutral' },
    'd\u2019accord': { en: 'okay / agreed', register: 'neutral' },
    'pas question': { en: 'no way', register: 'informal' },
    'tout à fait': { en: 'exactly / absolutely', register: 'neutral' },
};
